package demo5;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.02.09 15:38:08 // Generated by ComTest
 *
 */
public class LinjaAutoTest {



  // Generated by ComTest BEGIN
  /** testLinjaAuto16 */
  @Test
  public void testLinjaAuto16() {    // LinjaAuto: 16
    LinjaAuto a = new LinjaAuto(31); 
    assertEquals("From: LinjaAuto line: 18", 31, a.getMaara(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMaara28 */
  @Test
  public void testGetMaara28() {    // LinjaAuto: 28
    LinjaAuto a = new LinjaAuto(31); 
    assertEquals("From: LinjaAuto line: 30", 31, a.getMaara(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVahenna42 */
  @Test
  public void testVahenna42() {    // LinjaAuto: 42
    LinjaAuto a = new LinjaAuto(31); 
    a.vahenna(3); 
    assertEquals("From: LinjaAuto line: 45", 28, a.getMaara(), 0.000001); 
  } // Generated by ComTest END
}