package demo4;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo4.Kolmio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.01.30 15:46:11 // Generated by ComTest
 *
 */
public class KolmioTest {



  // Generated by ComTest BEGIN
  /** testKolmionAla39 */
  @Test
  public void testKolmionAla39() {    // Kolmio: 39
    assertEquals("From: Kolmio line: 40", 0, kolmionAla(0, 1), 0.000001); 
    assertEquals("From: Kolmio line: 41", 2, kolmionAla(2, 2), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHypotenuusa55 */
  @Test
  public void testHypotenuusa55() {    // Kolmio: 55
    assertEquals("From: Kolmio line: 57", 0.0, hypotenuusa(0,0), 0.01); 
    assertEquals("From: Kolmio line: 58", 1.41, hypotenuusa(1,1), 0.01); 
    assertEquals("From: Kolmio line: 59", 7.81, hypotenuusa(5,6), 0.01); 
  } // Generated by ComTest END
}