package demo4;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo4.Tauno.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.01.30 12:41:46 // Generated by ComTest
 *
 */
public class TaunoTest {



  // Generated by ComTest BEGIN
  /** testKasitteleTaulukko31 */
  @Test
  public void testKasitteleTaulukko31() {    // Tauno: 31
    int[] t; 
    t = new int[]{55, 44, 33, 2, 5, 9}; KasitteleTaulukko(t); assertEquals("From: Tauno line: 37", "[60, 49, 38, 7, 10, 14]", Arrays.toString(t));  
    t = new int[]{23, 45, -12, 9, 0, -5}; KasitteleTaulukko(t); assertEquals("From: Tauno line: 38", "[28, 50, -7, 14, 5, 0]", Arrays.toString(t));  
  } // Generated by ComTest END
}