package demo4;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo4.Tauno1.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.01.30 12:45:57 // Generated by ComTest
 *
 */
public class Tauno1Test {



  // Generated by ComTest BEGIN
  /** testKasitteleTaulukko31 */
  @Test
  public void testKasitteleTaulukko31() {    // Tauno1: 31
    int[] t; 
    t = new int[]{5, 4, 6, 2, 9, 1}; KasitteleTaulukko(t); assertEquals("From: Tauno1 line: 37", "[9, 0, 8, 0, 10, 0]", Arrays.toString(t));  
    t = new int[]{12, 3, 5, -5, 7, 10}; KasitteleTaulukko(t); assertEquals("From: Tauno1 line: 38", "[15, 0, 0, 0, 17, 0]", Arrays.toString(t));  
  } // Generated by ComTest END
}